<#
.SYNOPSIS
    Turns tools\strings\*.txt into the .resx files the app embeds and the Strings accessor it calls.

.DESCRIPTION
    en.txt is the source of truth: every key in it becomes a property on AntiPilot.Strings, so a
    typo in calling code is a compile error rather than a blank label at runtime. Each other
    <tag>.txt is a translation and needs only the keys it actually translates — ResourceManager
    falls back to the neutral (English) resource for the rest.

    Run this after editing any file under tools\strings.
#>
[CmdletBinding()]
param(
    [string]$StringsDir = (Join-Path $PSScriptRoot 'strings'),
    [string]$ResourceDir = (Join-Path $PSScriptRoot '..\src\AntiPilot\Resources'),
    [string]$AccessorPath = (Join-Path $PSScriptRoot '..\src\AntiPilot\Strings.g.cs'),

    # Fails instead of writing when a translation carries a key English does not have, or when a
    # format string has lost a placeholder. Used by CI.
    [switch]$CheckOnly
)

$ErrorActionPreference = 'Stop'

function Read-StringTable([string]$path) {
    $table = [ordered]@{}
    $lineNumber = 0

    foreach ($line in Get-Content -LiteralPath $path -Encoding UTF8) {
        $lineNumber++
        $trimmed = $line.Trim()
        if ($trimmed.Length -eq 0 -or $trimmed.StartsWith('#')) { continue }

        $split = $trimmed.IndexOf('=')
        if ($split -lt 1) { throw "${path}:${lineNumber}: expected 'Key = value'." }

        $key = $trimmed.Substring(0, $split).Trim()
        $value = $trimmed.Substring($split + 1).Trim()

        if ($table.Contains($key)) { throw "${path}:${lineNumber}: duplicate key '$key'." }
        $table[$key] = $value -replace '\\n', "`n"
    }

    return $table
}

# The placeholders a string uses, so a translation cannot quietly drop one and crash string.Format.
function Get-Placeholders([string]$value) {
    [regex]::Matches($value, '\{(\d+)\}') | ForEach-Object { [int]$_.Groups[1].Value } | Sort-Object -Unique
}

$resxHeader = @'
<?xml version="1.0" encoding="utf-8"?>
<root>
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence><xsd:element name="value" type="xsd:string" minOccurs="0" /></xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence><xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" /></xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
'@

function Write-Resx([string]$path, $table, [string]$sourceName) {
    $builder = [Text.StringBuilder]::new()
    [void]$builder.AppendLine($resxHeader)
    [void]$builder.AppendLine("  <!-- Generated by tools\Update-Strings.ps1 from tools\strings\$sourceName. Do not edit. -->")

    foreach ($key in $table.Keys) {
        $escaped = [Security.SecurityElement]::Escape($table[$key])
        [void]$builder.AppendLine("  <data name=""$key"" xml:space=""preserve"">")
        [void]$builder.AppendLine("    <value>$escaped</value>")
        [void]$builder.AppendLine('  </data>')
    }

    [void]$builder.AppendLine('</root>')

    $text = $builder.ToString() -replace "`r`n", "`n" -replace "`n", "`r`n"
    if ($CheckOnly) { return }
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $path) | Out-Null
    [IO.File]::WriteAllText($path, $text, [Text.UTF8Encoding]::new($false))
}

$englishPath = Join-Path $StringsDir 'en.txt'
if (-not (Test-Path -LiteralPath $englishPath)) { throw "Missing $englishPath." }
$english = Read-StringTable $englishPath
Write-Host "en.txt: $($english.Count) strings" -ForegroundColor Cyan

$problems = [Collections.Generic.List[string]]::new()
$translations = Get-ChildItem -LiteralPath $StringsDir -Filter '*.txt' |
    Where-Object { $_.Name -ne 'en.txt' } | Sort-Object Name

foreach ($file in $translations) {
    $tag = [IO.Path]::GetFileNameWithoutExtension($file.Name)
    $table = Read-StringTable $file.FullName

    foreach ($key in $table.Keys) {
        if (-not $english.Contains($key)) {
            $problems.Add("$($file.Name): key '$key' does not exist in en.txt.")
            continue
        }

        $wanted = @(Get-Placeholders $english[$key])
        $got = @(Get-Placeholders $table[$key])
        if (Compare-Object $wanted $got) {
            $problems.Add("$($file.Name): '$key' uses placeholders {$($got -join ',')} but English uses {$($wanted -join ',')}.")
        }
    }

    $missing = @($english.Keys | Where-Object { -not $table.Contains($_) })
    $coverage = [math]::Round(($english.Count - $missing.Count) / $english.Count * 100)
    Write-Host ("{0,-8} {1,3}/{2} translated ({3}%)" -f $tag, ($english.Count - $missing.Count), $english.Count, $coverage)

    Write-Resx (Join-Path $ResourceDir "Strings.$tag.resx") $table $file.Name
}

if ($problems.Count -gt 0) {
    $problems | ForEach-Object { Write-Host "  $_" -ForegroundColor Red }
    throw "$($problems.Count) problem(s) in the string tables."
}

Write-Resx (Join-Path $ResourceDir 'Strings.resx') $english 'en.txt'

# ---- the accessor -----------------------------------------------------------

$accessor = [Text.StringBuilder]::new()
[void]$accessor.AppendLine(@'
// <auto-generated>
//     Generated by tools\Update-Strings.ps1 from tools\strings\en.txt. Do not edit.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace AntiPilot;

/// <summary>
/// Every user-visible string in the app. English lives in Resources\Strings.resx and is compiled
/// into the executable, so a missing translation degrades to English rather than to a blank label.
/// </summary>
public static partial class Strings
{
    private static readonly ResourceManager Resources =
        new("AntiPilot.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>
    /// The language to look strings up in. Null follows Windows. Set once at start-up from
    /// <see cref="AppConfig.Language"/>; changing it later does not relabel windows already open.
    /// </summary>
    public static CultureInfo? Culture { get; set; }

    /// <summary>Looks up one string. Never throws: a missing key shows as !Key! instead.</summary>
    public static string Get(string key)
    {
        try
        {
            return Resources.GetString(key, Culture) ?? $"!{key}!";
        }
        catch (Exception)
        {
            return $"!{key}!";
        }
    }

    /// <summary>Shorthand for a string that carries {0}-style placeholders.</summary>
    public static string Format(string value, params object?[] arguments) =>
        string.Format(Culture ?? CultureInfo.CurrentUICulture, value, arguments);
'@)

foreach ($key in $english.Keys) {
    $comment = $english[$key] -replace "`n", ' '
    if ($comment.Length -gt 96) { $comment = $comment.Substring(0, 93) + '...' }
    [void]$accessor.AppendLine()
    [void]$accessor.AppendLine("    /// <summary>$([Security.SecurityElement]::Escape($comment))</summary>")
    [void]$accessor.AppendLine("    public static string $key => Get(""$key"");")
}

[void]$accessor.AppendLine('}')

if (-not $CheckOnly) {
    $text = $accessor.ToString() -replace "`r`n", "`n" -replace "`n", "`r`n"
    [IO.File]::WriteAllText($AccessorPath, $text, [Text.UTF8Encoding]::new($false))
}

$verb = if ($CheckOnly) { 'Checked' } else { 'Wrote' }
Write-Host "$verb $($english.Count) strings, $($translations.Count) translation(s)." -ForegroundColor Green
