// <auto-generated>
//     Generated by tools\Update-Strings.ps1 from tools\strings\en.txt. Do not edit.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace AntiPilot;

/// <summary>
/// Every user-visible string in the app. English lives in Resources\Strings.resx and is compiled
/// into the executable, so a missing translation degrades to English rather than to a blank label.
/// </summary>
public static partial class Strings
{
    private static readonly ResourceManager Resources =
        new("AntiPilot.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>
    /// The language to look strings up in. Null follows Windows. Set once at start-up from
    /// <see cref="AppConfig.Language"/>; changing it later does not relabel windows already open.
    /// </summary>
    public static CultureInfo? Culture { get; set; }

    /// <summary>Looks up one string. Never throws: a missing key shows as !Key! instead.</summary>
    public static string Get(string key)
    {
        try
        {
            return Resources.GetString(key, Culture) ?? $"!{key}!";
        }
        catch (Exception)
        {
            return $"!{key}!";
        }
    }

    /// <summary>Shorthand for a string that carries {0}-style placeholders.</summary>
    public static string Format(string value, params object?[] arguments) =>
        string.Format(Culture ?? CultureInfo.CurrentUICulture, value, arguments);

    /// <summary>AntiPilot</summary>
    public static string AppName => Get("AppName");

    /// <summary>Nothing</summary>
    public static string Nothing => Get("Nothing");

    /// <summary>(no app)</summary>
    public static string NoApp => Get("NoApp");

    /// <summary>(no app chosen)</summary>
    public static string NoAppChosen => Get("NoAppChosen");

    /// <summary>OK</summary>
    public static string Ok => Get("Ok");

    /// <summary>Cancel</summary>
    public static string Cancel => Get("Cancel");

    /// <summary>Save</summary>
    public static string Save => Get("Save");

    /// <summary>Remove</summary>
    public static string Remove => Get("Remove");

    /// <summary>Add</summary>
    public static string Add => Get("Add");

    /// <summary>Close</summary>
    public static string Close => Get("Close");

    /// <summary>Edit</summary>
    public static string Edit => Get("Edit");

    /// <summary>Menu key</summary>
    public static string MenuKeyShort => Get("MenuKeyShort");

    /// <summary>Quick-launch palette</summary>
    public static string PaletteShort => Get("PaletteShort");

    /// <summary>Keyboard shortcut</summary>
    public static string HotkeyShort => Get("HotkeyShort");

    /// <summary>AntiPilot</summary>
    public static string SettingsTitle => Get("SettingsTitle");

    /// <summary>Decide what the Copilot key (and Win+C) actually does.</summary>
    public static string SettingsTagline => Get("SettingsTagline");

    /// <summary>Open Windows settings</summary>
    public static string OpenWindowsSettings => Get("OpenWindowsSettings");

    /// <summary>Single press</summary>
    public static string TabSinglePress => Get("TabSinglePress");

    /// <summary>Double press</summary>
    public static string TabDoublePress => Get("TabDoublePress");

    /// <summary>Per-app</summary>
    public static string TabPerApp => Get("TabPerApp");

    /// <summary>Palette</summary>
    public static string TabPalette => Get("TabPalette");

    /// <summary>General</summary>
    public static string TabGeneral => Get("TabGeneral");

    /// <summary>Startup and language</summary>
    public static string GeneralGroupBehaviour => Get("GeneralGroupBehaviour");

    /// <summary>Settings file</summary>
    public static string GeneralGroupTransfer => Get("GeneralGroupTransfer");

    /// <summary>About</summary>
    public static string GeneralGroupAbout => Get("GeneralGroupAbout");

    /// <summary>Every key press, and why anything that failed did</summary>
    public static string OpenLogDescription => Get("OpenLogDescription");

    /// <summary>A way back to this window that does not need the Start menu</summary>
    public static string TrayDescription => Get("TrayDescription");

    /// <summary>Do this:</summary>
    public static string DoThis => Get("DoThis");

    /// <summary>Test it</summary>
    public static string TestIt => Get("TestIt");

    /// <summary>Open log</summary>
    public static string OpenLog => Get("OpenLog");

    /// <summary>About</summary>
    public static string About => Get("About");

    /// <summary>Import / export</summary>
    public static string ImportExport => Get("ImportExport");

    /// <summary>The key does nothing at all. Pick something above.</summary>
    public static string NothingHintTap => Get("NothingHintTap");

    /// <summary>A double press does the same as a single one.</summary>
    public static string NothingHintDouble => Get("NothingHintDouble");

    /// <summary>Show the tray icon, and start it when I sign in</summary>
    public static string ShowTrayAndStart => Get("ShowTrayAndStart");

    /// <summary>Tray icon at sign-in (needs the installed version)</summary>
    public static string TrayNeedsInstall => Get("TrayNeedsInstall");

    /// <summary>Tray icon at sign-in (switched off in Task Manager)</summary>
    public static string TrayBlocked => Get("TrayBlocked");

    /// <summary>Save your changes before closing?</summary>
    public static string SaveBeforeClosing => Get("SaveBeforeClosing");

    /// <summary>Could not save settings.</summary>
    public static string CouldNotSave => Get("CouldNotSave");

    /// <summary>Nothing is configured yet.</summary>
    public static string NothingConfiguredYet => Get("NothingConfiguredYet");

    /// <summary>The Menu key action can only be tested from the keyboard: close this window, focus something ...</summary>
    public static string MenuKeyTestHint => Get("MenuKeyTestHint");

    /// <summary>A keyboard shortcut can only be tested from the keyboard: close this window, focus something ...</summary>
    public static string HotkeyTestHint => Get("HotkeyTestHint");

    /// <summary>Language</summary>
    public static string Language => Get("Language");

    /// <summary>Same as Windows</summary>
    public static string LanguageSystem => Get("LanguageSystem");

    /// <summary>The new language appears the next time the window opens.</summary>
    public static string LanguageRestartHint => Get("LanguageRestartHint");

    /// <summary>Debug build — Windows only sees the installed MSIX.</summary>
    public static string StatusUnpackaged => Get("StatusUnpackaged");

    /// <summary>The Copilot key and Win+C run AntiPilot.</summary>
    public static string StatusActive => Get("StatusActive");

    /// <summary>The Copilot key opens Search — pick AntiPilot →</summary>
    public static string StatusSearch => Get("StatusSearch");

    /// <summary>The Copilot key opens another app — pick AntiPilot →</summary>
    public static string StatusOtherApp => Get("StatusOtherApp");

    /// <summary>The Copilot key still does its default thing →</summary>
    public static string StatusDefault => Get("StatusDefault");

    /// <summary>Nothing</summary>
    public static string ModeNothing => Get("ModeNothing");

    /// <summary>Launch an installed app  (Start menu or Microsoft Store)</summary>
    public static string ModeShellApp => Get("ModeShellApp");

    /// <summary>Launch a program, file, folder or link</summary>
    public static string ModeFile => Get("ModeFile");

    /// <summary>Act as the Menu key  (the old context-menu key)</summary>
    public static string ModeMenuKey => Get("ModeMenuKey");

    /// <summary>Send a keyboard shortcut</summary>
    public static string ModeHotkey => Get("ModeHotkey");

    /// <summary>Show the quick-launch palette</summary>
    public static string ModePalette => Get("ModePalette");

    /// <summary>Choose app…</summary>
    public static string ChooseApp => Get("ChooseApp");

    /// <summary>Browse…</summary>
    public static string Browse => Get("Browse");

    /// <summary>Anything in the Start menu&apos;s app list works here, including Microsoft Store apps.</summary>
    public static string AppHint => Get("AppHint");

    /// <summary>Program, file, folder or link</summary>
    public static string FileCaptionPath => Get("FileCaptionPath");

    /// <summary>Arguments (optional)</summary>
    public static string FileCaptionArgs => Get("FileCaptionArgs");

    /// <summary>Start in (optional)</summary>
    public static string FileCaptionWorkDir => Get("FileCaptionWorkDir");

    /// <summary>Environment variables such as %USERPROFILE% are expanded.</summary>
    public static string FileHint => Get("FileHint");

    /// <summary>C:\Windows\System32 otepad.exe   or   https://example.com</summary>
    public static string FilePlaceholder => Get("FilePlaceholder");

    /// <summary>Pick a program or file</summary>
    public static string FileDialogTitle => Get("FileDialogTitle");

    /// <summary>Programs and shortcuts|*.exe;*.lnk;*.bat;*.cmd;*.ps1;*.url|All files|*.*</summary>
    public static string FileDialogFilter => Get("FileDialogFilter");

    /// <summary>The key sends the Menu key (VK_APPS), so the context menu of whatever is focused opens — exac...</summary>
    public static string MenuKeyBody => Get("MenuKeyBody");

    /// <summary>Windows blocks synthetic input aimed at windows running as administrator, so this does nothin...</summary>
    public static string ElevatedHint => Get("ElevatedHint");

    /// <summary>The key opens a small list of your palette entries. Type to filter, press 1-9 to run an entry...</summary>
    public static string PaletteBody => Get("PaletteBody");

    /// <summary>The palette has no entries yet. Add some on the Palette tab.</summary>
    public static string PaletteEmptyWarning => Get("PaletteEmptyWarning");

    /// <summary>When it is already running:</summary>
    public static string WhenAlreadyRunning => Get("WhenAlreadyRunning");

    /// <summary>Start another copy</summary>
    public static string BehaviourAlways => Get("BehaviourAlways");

    /// <summary>Bring the existing window to the front</summary>
    public static string BehaviourFocus => Get("BehaviourFocus");

    /// <summary>Bring it to the front, or minimise it if it is already there</summary>
    public static string BehaviourToggle => Get("BehaviourToggle");

    /// <summary>Focusing an existing window needs the app to be running as you, not as administrator.</summary>
    public static string BehaviourHint => Get("BehaviourHint");

    /// <summary>Shortcut to send</summary>
    public static string HotkeyCaption => Get("HotkeyCaption");

    /// <summary>Click here, then press the shortcut</summary>
    public static string HotkeyPlaceholder => Get("HotkeyPlaceholder");

    /// <summary>Press the shortcut now…</summary>
    public static string HotkeyRecording => Get("HotkeyRecording");

    /// <summary>Clear</summary>
    public static string HotkeyClear => Get("HotkeyClear");

    /// <summary>Sent to whatever has focus. Modifiers on their own are not a shortcut — add a normal key.</summary>
    public static string HotkeyHint => Get("HotkeyHint");

    /// <summary>Presets:</summary>
    public static string HotkeyPresets => Get("HotkeyPresets");

    /// <summary>That is not a shortcut AntiPilot can send.</summary>
    public static string HotkeyInvalid => Get("HotkeyInvalid");

    /// <summary>Task Manager</summary>
    public static string PresetTaskManager => Get("PresetTaskManager");

    /// <summary>Clipboard history</summary>
    public static string PresetClipboard => Get("PresetClipboard");

    /// <summary>Screen snip</summary>
    public static string PresetSnip => Get("PresetSnip");

    /// <summary>File Explorer</summary>
    public static string PresetExplorer => Get("PresetExplorer");

    /// <summary>Emoji panel</summary>
    public static string PresetEmoji => Get("PresetEmoji");

    /// <summary>Print screen</summary>
    public static string PresetPrintScreen => Get("PresetPrintScreen");

    /// <summary>Lock the PC</summary>
    public static string PresetLock => Get("PresetLock");

    /// <summary>Show the desktop</summary>
    public static string PresetShowDesktop => Get("PresetShowDesktop");

    /// <summary>Play / pause</summary>
    public static string PresetPlayPause => Get("PresetPlayPause");

    /// <summary>Mute</summary>
    public static string PresetMute => Get("PresetMute");

    /// <summary>Choose an app</summary>
    public static string PickerTitle => Get("PickerTitle");

    /// <summary>Search apps</summary>
    public static string PickerSearch => Get("PickerSearch");

    /// <summary>Reading the app list…</summary>
    public static string PickerLoading => Get("PickerLoading");

    /// <summary>{0} apps</summary>
    public static string PickerCount => Get("PickerCount");

    /// <summary>Nothing matches that.</summary>
    public static string PickerNoMatch => Get("PickerNoMatch");

    /// <summary>App</summary>
    public static string PickerColumnApp => Get("PickerColumnApp");

    /// <summary>Select</summary>
    public static string PickerSelect => Get("PickerSelect");

    /// <summary>Could not read the list of installed apps.</summary>
    public static string PickerFailed => Get("PickerFailed");

    /// <summary>Give the key a different job while a particular app is in front. Rules are tried top to botto...</summary>
    public static string PerAppIntro => Get("PerAppIntro");

    /// <summary>When this is in front</summary>
    public static string PerAppColumnApp => Get("PerAppColumnApp");

    /// <summary>The key does this</summary>
    public static string PerAppColumnAction => Get("PerAppColumnAction");

    /// <summary>Add rule…</summary>
    public static string PerAppAdd => Get("PerAppAdd");

    /// <summary>Change action…</summary>
    public static string PerAppEditAction => Get("PerAppEditAction");

    /// <summary>Process name</summary>
    public static string PerAppProcess => Get("PerAppProcess");

    /// <summary>The executable name, with or without .exe — for example chrome or devenv.</summary>
    public static string PerAppProcessHint => Get("PerAppProcessHint");

    /// <summary>Pick a running app…</summary>
    public static string PerAppPickRunning => Get("PerAppPickRunning");

    /// <summary>No rules yet. The key does the same thing everywhere.</summary>
    public static string PerAppNoRules => Get("PerAppNoRules");

    /// <summary>There is already a rule for that app.</summary>
    public static string PerAppDuplicate => Get("PerAppDuplicate");

    /// <summary>Entries offered when an action is set to &quot;Show the quick-launch palette&quot;. The first nine can ...</summary>
    public static string PaletteIntro => Get("PaletteIntro");

    /// <summary>Name</summary>
    public static string PaletteColumnLabel => Get("PaletteColumnLabel");

    /// <summary>Runs</summary>
    public static string PaletteColumnAction => Get("PaletteColumnAction");

    /// <summary>Add entry…</summary>
    public static string PaletteAdd => Get("PaletteAdd");

    /// <summary>Move up</summary>
    public static string PaletteMoveUp => Get("PaletteMoveUp");

    /// <summary>Move down</summary>
    public static string PaletteMoveDown => Get("PaletteMoveDown");

    /// <summary>No entries yet.</summary>
    public static string PaletteNoEntries => Get("PaletteNoEntries");

    /// <summary>Name (optional)</summary>
    public static string PaletteLabelCaption => Get("PaletteLabelCaption");

    /// <summary>AntiPilot</summary>
    public static string PaletteWindowTitle => Get("PaletteWindowTitle");

    /// <summary>Type to filter…</summary>
    public static string PaletteFilterPlaceholder => Get("PaletteFilterPlaceholder");

    /// <summary>Nothing matches.</summary>
    public static string PaletteNoMatch => Get("PaletteNoMatch");

    /// <summary>Give two quick presses their own action</summary>
    public static string DoubleTapEnable => Get("DoubleTapEnable");

    /// <summary>A second press inside the window below runs the action set at the bottom of this page.</summary>
    public static string DoubleTapEnableDescription => Get("DoubleTapEnableDescription");

    /// <summary>A single press has to wait {0} ms to find out whether a second one is coming, so every press ...</summary>
    public static string DoubleTapCostWarning => Get("DoubleTapCostWarning");

    /// <summary>Wait for the second press for</summary>
    public static string DoubleTapWindow => Get("DoubleTapWindow");

    /// <summary>{0} ms</summary>
    public static string DoubleTapMilliseconds => Get("DoubleTapMilliseconds");

    /// <summary>Two quick presses just run the single-press action twice.</summary>
    public static string DoubleTapDisabledHint => Get("DoubleTapDisabledHint");

    /// <summary>Export AntiPilot settings</summary>
    public static string ExportTitle => Get("ExportTitle");

    /// <summary>Import AntiPilot settings</summary>
    public static string ImportTitle => Get("ImportTitle");

    /// <summary>AntiPilot settings|*.json|All files|*.*</summary>
    public static string ConfigFilter => Get("ConfigFilter");

    /// <summary>Settings exported.</summary>
    public static string ExportDone => Get("ExportDone");

    /// <summary>That file is not a readable AntiPilot settings file.</summary>
    public static string ImportFailed => Get("ImportFailed");

    /// <summary>Replace your current settings with the ones in this file?</summary>
    public static string ImportConfirm => Get("ImportConfirm");

    /// <summary>Settings imported.</summary>
    public static string ImportDone => Get("ImportDone");

    /// <summary>Export…</summary>
    public static string ExportButton => Get("ExportButton");

    /// <summary>Import…</summary>
    public static string ImportButton => Get("ImportButton");

    /// <summary>Settings…</summary>
    public static string TraySettings => Get("TraySettings");

    /// <summary>Run the key action</summary>
    public static string TrayRunAction => Get("TrayRunAction");

    /// <summary>Run: {0}</summary>
    public static string TrayRunNamed => Get("TrayRunNamed");

    /// <summary>Nothing configured</summary>
    public static string TrayNothingConfigured => Get("TrayNothingConfigured");

    /// <summary>Customise the Copilot key in Windows…</summary>
    public static string TrayCustomiseKey => Get("TrayCustomiseKey");

    /// <summary>Start when I sign in</summary>
    public static string TrayStartWithSignIn => Get("TrayStartWithSignIn");

    /// <summary>Start when I sign in (off in Task Manager)</summary>
    public static string TrayStartBlocked => Get("TrayStartBlocked");

    /// <summary>About AntiPilot…</summary>
    public static string TrayAbout => Get("TrayAbout");

    /// <summary>Exit</summary>
    public static string TrayExit => Get("TrayExit");

    /// <summary>AntiPilot — {0}</summary>
    public static string TrayTooltip => Get("TrayTooltip");

    /// <summary>not set up yet</summary>
    public static string TrayNotSetUp => Get("TrayNotSetUp");

    /// <summary>AntiPilot is in the notification area</summary>
    public static string TrayIntroTitle => Get("TrayIntroTitle");

    /// <summary>Windows hides new icons: click the ^ next to the clock and drag AntiPilot onto the taskbar to...</summary>
    public static string TrayIntroBody => Get("TrayIntroBody");

    /// <summary>The Menu key action only makes sense when you press the key yourself.</summary>
    public static string TrayMenuKeyOnly => Get("TrayMenuKeyOnly");

    /// <summary>Windows remembers that this was switched off in Task Manager, and only you can switch it back...</summary>
    public static string TrayStartupBlockedBody => Get("TrayStartupBlockedBody");

    /// <summary>Windows would not enable the startup task.</summary>
    public static string TrayStartupFailed => Get("TrayStartupFailed");

    /// <summary>Could not start the tray icon.</summary>
    public static string TrayCouldNotStart => Get("TrayCouldNotStart");

    /// <summary>AntiPilot could not run the action</summary>
    public static string ActionFailedTitle => Get("ActionFailedTitle");

    /// <summary>{0}</summary>
    public static string ActionFailedBody => Get("ActionFailedBody");

    /// <summary>That app is no longer installed.</summary>
    public static string TargetMissingApp => Get("TargetMissingApp");

    /// <summary>That file or folder is no longer there.</summary>
    public static string TargetMissingFile => Get("TargetMissingFile");

    /// <summary>Check this before saving</summary>
    public static string ValidationTitle => Get("ValidationTitle");

    /// <summary>Save anyway</summary>
    public static string ValidationContinue => Get("ValidationContinue");

    /// <summary>About AntiPilot</summary>
    public static string AboutTitle => Get("AboutTitle");

    /// <summary>Version {0}</summary>
    public static string AboutVersion => Get("AboutVersion");

    /// <summary>Version unknown</summary>
    public static string AboutVersionUnknown => Get("AboutVersionUnknown");

    /// <summary>Running unpackaged</summary>
    public static string AboutUnpackaged => Get("AboutUnpackaged");

    /// <summary>Makes the Copilot key launch an app of your choice, send a shortcut, or act as the Menu key.</summary>
    public static string AboutTagline => Get("AboutTagline");
}
